# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'Runner' do
  # Pods for Runner
  use_frameworks!
  platform :ios, '12.0'
  pod 'shared', :path => '../shared'
end

